### ISSUE TITLE
Is it not working anymore?

### ISSUE THREAD

**Issue by Techcatchers** [gautamkrishnar/Be-Like-Bill#25]
I saw this API and wanted to implement it but it seems you have closed this project. Have you started an alternative solution for this?

**Comment by gautamkrishnar** [comment]
As of now my azure subscription is in expired state. Thats why the API is not available. I am looking for a free alternative.

**Comment by Techcatchers** [comment]
You can try GCP which offers 365 day free trial.

**Comment by gautamkrishnar** [comment]
Hi @Techcatchers as of now i had deployed it to http://belikebill-belikebill.1d35.starter-us-east-1.openshiftapps.com/. Will look into GCP later. Please feel free to host it yourself on your server if you need to use it for production purposes.

**Comment by gautamkrishnar** [comment]
https://www.belikebill.ga/ is the latest domain. You can use this.

**Comment by Techcatchers** [comment]
Thanks a lot dude...
Regards
Rishabh Agrawal
