### ISSUE TITLE
typo in memelist.php

### ISSUE THREAD

**Issue by gautamkrishnar** [gautamkrishnar/Be-Like-Bill#26]
Fix the typo: https://github.com/gautamkrishnar/Be-Like-Bill/blob/master/memelist.php#L40

`Bill doesnt't forget good manners \n` -> `Bill doesn't forget good manners \n`

**Comment by smokes** [comment]
i'll do it

**Comment by gautamkrishnar** [comment]
@imsmokie you are welcome 😄
