### ISSUE TITLE
Text overlaps on the image if the text is too lengthy. Break the text

### ISSUE THREAD

**Issue by riginoommen** [gautamkrishnar/Be-Like-Bill#6]

**Comment by gautamkrishnar** [comment]
Yes. Its a bug. Thanks for reporting. I will try to fix it in the API level. :smile:

**Comment by gautamkrishnar** [comment]
Added word warp and it is live on production server :smile:

**Comment by riginoommen** [comment]
Awesome

Regards

Rigin Oommen
