### ISSUE TITLE
fb share

### ISSUE THREAD

**Issue by luka5001** [gautamkrishnar/Be-Like-Bill#8]
hi pls add fb share button than people  well share picture link

**Comment by gautamkrishnar** [comment]
Thanks @luka5001. I was also thinking about implementing it. I will try to make that possible soon... :smile:

**Comment by luka5001** [comment]
i was try but ................. :D
how many time well make ?

On Fri, Jun 17, 2016 at 10:54 AM, Gautam krishna.R <notifications@github.com

**Comment by gautamkrishnar** [comment]
Yes its a little hard one. We actually need a facebook app with post permission to upload photos to facebook :smiling_imp:

**Comment by luka5001** [comment]
hello gautamkrishnar 
plase get me 
be like willi script

**Comment by luka5001** [comment]
i need it very much  <3

**Comment by gautamkrishnar** [comment]
@luka5001  here's the code from the developer 
https://drive.google.com/file/d/0BxTo7lsyjGX1b1duUU05YXprS0hFLXl2MlpPQm1SenNGLUsw/view?usp=drive_web

**Comment by gautamkrishnar** [comment]
@luka5001  It is now available
